#include "../src/reactiveInterface/reactiveInterfaceGeometry.h"
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <vector>
using namespace ReactiveInterfaceGeometry;
static void ck(cudaError_t e,const char*m){if(e!=cudaSuccess){std::cerr<<m<<": "<<cudaGetErrorString(e)<<"\n";std::exit(2);}}
static Boundaries periodic(){Boundaries b{};for(int a=0;a<3;++a)b.low[a]=b.high[a]={BoundaryMode::periodic,0};return b;}
int main(){
  StructuredGrid g{18,14,12,.03,.03,.03};auto b=periodic();const auto n=cells(g);std::vector<double> color(n);
  for(int k=0;k<g.nz;++k)for(int j=0;j<g.ny;++j)for(int i=0;i<g.nx;++i){double x=(i+.5-g.nx/2.)*g.dx,y=(j+.5-g.ny/2.)*g.dy,z=(k+.5-g.nz/2.)*g.dz;color[cell(g,i,j,k)]=.5*(1-std::tanh((std::sqrt(x*x+y*y+z*z)-.10)/(.045)));}
  std::vector<std::vector<double>> host(18,std::vector<double>(n)),gpu(18,std::vector<double>(n));
  GeometryWorkspaceView hg{host[0].data(),host[1].data(),host[2].data(),host[3].data(),host[4].data(),host[5].data(),host[6].data(),host[7].data()};
  CapillaryWorkspaceView hc{host[8].data(),host[9].data(),host[10].data(),host[11].data(),host[12].data(),host[13].data(),host[14].data(),host[15].data(),host[16].data(),host[17].data()};
  InterfaceOptions o{1e-14,.8,true};ExecutionCounters cc{};if(computeGeometryCpu(color.data(),g,b,o,.072,hg,&hc,cc)!=Status::ok)return 2;
  double* dc=nullptr;int* dgeomStatus=nullptr;ck(cudaMalloc(&dc,n*sizeof(double)),"color alloc");ck(cudaMalloc(&dgeomStatus,sizeof(int)),"status alloc");ck(cudaMemcpy(dc,color.data(),n*sizeof(double),cudaMemcpyHostToDevice),"color copy");std::vector<double*> dpOff(7);for(auto&p:dpOff)ck(cudaMalloc(&p,n*sizeof(double)),"off-only workspace alloc");GeometryWorkspaceView offOnlyView{dpOff[0],dpOff[1],dpOff[2],dpOff[3],dpOff[4],dpOff[5],dpOff[6],nullptr};InterfaceOptions offOnlyOpt{1e-14,.8,false};ExecutionCounters offOnlyCount{};if(computeGeometryCuda(dc,g,b,offOnlyOpt,.072,offOnlyView,nullptr,dgeomStatus,offOnlyCount)!=Status::ok)return 2;ck(cudaDeviceSynchronize(),"off-only sync");for(auto p:dpOff)cudaFree(p);std::vector<double*> dp(18);for(auto&p:dp)ck(cudaMalloc(&p,n*sizeof(double)),"workspace alloc");
  GeometryWorkspaceView dg{dp[0],dp[1],dp[2],dp[3],dp[4],dp[5],dp[6],dp[7]};CapillaryWorkspaceView dcw{dp[8],dp[9],dp[10],dp[11],dp[12],dp[13],dp[14],dp[15],dp[16],dp[17]};ExecutionCounters gc{};
  if(computeGeometryCuda(dc,g,b,o,.072,dg,&dcw,dgeomStatus,gc)!=Status::ok)return 2;ck(cudaDeviceSynchronize(),"geometry sync");for(int q=0;q<18;++q)ck(cudaMemcpy(gpu[q].data(),dp[q],n*sizeof(double),cudaMemcpyDeviceToHost),"result copy");
  double maxerr=0;for(int q=0;q<18;++q)for(std::size_t i=0;i<n;++i)maxerr=std::max(maxerr,std::fabs(host[q][i]-gpu[q][i]));if(maxerr>2e-12){std::cerr<<"parity "<<maxerr<<"\n";return 2;}
  InterfaceOptions off{1e-14,.8,false};GeometryWorkspaceView dgo{dp[0],dp[1],dp[2],dp[3],dp[4],dp[5],dp[6],nullptr};ExecutionCounters offc{};if(computeGeometryCuda(dc,g,b,off,.072,dgo,nullptr,dgeomStatus,offc)!=Status::ok)return 2;ck(cudaDeviceSynchronize(),"off sync");if(offc.capillaryKernels||offc.curvatureKernels){std::cerr<<"off launched capillary work\n";return 2;}
  double badColor=2;ck(cudaMemcpy(dc,&badColor,sizeof(double),cudaMemcpyHostToDevice),"bad color copy");ExecutionCounters badc{};if(computeGeometryCuda(dc,g,b,off,.072,dgo,nullptr,dgeomStatus,badc)!=Status::invalidInput){std::cerr<<"bad GPU color accepted\n";return 2;}ck(cudaMemcpy(dc,color.data(),n*sizeof(double),cudaMemcpyHostToDevice),"restore color");
  constexpr int reps=100;cudaEvent_t e0,e1;ck(cudaEventCreate(&e0),"event");ck(cudaEventCreate(&e1),"event");ExecutionCounters ton{},toff{};computeGeometryCuda(dc,g,b,o,.072,dg,&dcw,dgeomStatus,ton);computeGeometryCuda(dc,g,b,off,.072,dgo,nullptr,dgeomStatus,toff);ck(cudaDeviceSynchronize(),"warmup");ck(cudaEventRecord(e0),"record");for(int r=0;r<reps;++r)computeGeometryCuda(dc,g,b,o,.072,dg,&dcw,dgeomStatus,ton);ck(cudaEventRecord(e1),"record");ck(cudaEventSynchronize(e1),"timing sync");float onms;ck(cudaEventElapsedTime(&onms,e0,e1),"elapsed");ck(cudaEventRecord(e0),"record");for(int r=0;r<reps;++r)computeGeometryCuda(dc,g,b,off,.072,dgo,nullptr,dgeomStatus,toff);ck(cudaEventRecord(e1),"record");ck(cudaEventSynchronize(e1),"timing sync");float offms;ck(cudaEventElapsedTime(&offms,e0,e1),"elapsed");std::size_t commonBytes=7*n*sizeof(double),capBytes=11*n*sizeof(double);
  std::size_t xn=std::size_t(g.nx+1)*g.ny*g.nz,yn=std::size_t(g.ny+1)*g.nx*g.nz,zn=std::size_t(g.nz+1)*g.nx*g.ny;std::vector<double> qx(xn,.2*g.dy*g.dz),qy(yn),qz(zn),hpx(xn),hpy(yn),hpz(zn),hmx(xn),hmy(yn),hmz(zn),inv(n,2),hout(n),gout(n);FaceFluxView hf{qx.data(),qy.data(),qz.data(),hpx.data(),hpy.data(),hpz.data(),hmx.data(),hmy.data(),hmz.data()};ExecutionCounters ha{};if(advectColorUpwind(color.data(),inv.data(),hout.data(),g,b,.1*g.dx,hf,ha)!=Status::ok)return 2;
  double *dout,*dinv,*dqx,*dqy,*dqz,*dpx,*dpy,*dpz,*dmx,*dmy,*dmz;int*dstatus;ck(cudaMalloc(&dout,n*8),"advect");ck(cudaMalloc(&dinv,n*8),"advect");ck(cudaMalloc(&dqx,xn*8),"advect");ck(cudaMalloc(&dqy,yn*8),"advect");ck(cudaMalloc(&dqz,zn*8),"advect");ck(cudaMalloc(&dpx,xn*8),"advect");ck(cudaMalloc(&dpy,yn*8),"advect");ck(cudaMalloc(&dpz,zn*8),"advect");ck(cudaMalloc(&dmx,xn*8),"advect");ck(cudaMalloc(&dmy,yn*8),"advect");ck(cudaMalloc(&dmz,zn*8),"advect");ck(cudaMalloc(&dstatus,sizeof(int)),"advect");ck(cudaMemcpy(dinv,inv.data(),n*8,cudaMemcpyHostToDevice),"advect");ck(cudaMemcpy(dqx,qx.data(),xn*8,cudaMemcpyHostToDevice),"advect");ck(cudaMemset(dqy,0,yn*8),"advect");ck(cudaMemset(dqz,0,zn*8),"advect");FaceFluxView df{dqx,dqy,dqz,dpx,dpy,dpz,dmx,dmy,dmz};ExecutionCounters ga{};std::vector<double> sentinel(n,-9),sentinelBack(n);ck(cudaMemcpy(dout,sentinel.data(),n*8,cudaMemcpyHostToDevice),"sentinel");double invalidColor=2;ck(cudaMemcpy(dc,&invalidColor,sizeof(double),cudaMemcpyHostToDevice),"invalid advection color");if(advectColorUpwindCuda(dc,dinv,dout,g,b,.1*g.dx,df,dstatus,ga)!=Status::invalidInput)return 2;ck(cudaMemcpy(sentinelBack.data(),dout,n*8,cudaMemcpyDeviceToHost),"sentinel back");if(sentinelBack!=sentinel)return 2;ck(cudaMemcpy(dc,color.data(),n*8,cudaMemcpyHostToDevice),"restore advection color");if(advectColorUpwindCuda(dc,dinv,dout,g,b,.1*g.dx,df,dstatus,ga)!=Status::ok)return 2;ck(cudaMemcpy(gout.data(),dout,n*8,cudaMemcpyDeviceToHost),"advect");double adverr=0;for(std::size_t i=0;i<n;++i)adverr=std::max(adverr,std::fabs(hout[i]-gout[i]));if(adverr>2e-14)return 2;cudaFree(dout);cudaFree(dinv);cudaFree(dqx);cudaFree(dqy);cudaFree(dqz);cudaFree(dpx);cudaFree(dpy);cudaFree(dpz);cudaFree(dmx);cudaFree(dmy);cudaFree(dmz);cudaFree(dstatus);
  for(auto p:dp)cudaFree(p);cudaFree(dc);cudaFree(dgeomStatus);cudaEventDestroy(e0);cudaEventDestroy(e1);std::cout<<"PASS gpuMaxError="<<maxerr<<" gpuAdvectionMaxError="<<adverr<<" gpuGeometryKernels="<<gc.geometryKernels<<" gpuCurvatureKernels="<<gc.curvatureKernels<<" gpuCapillaryKernels="<<gc.capillaryKernels<<" offCapillaryKernels="<<offc.capillaryKernels<<" gpuTimingGrid=18x14x12 gpuRepeats="<<reps<<" gpuOnUs="<<1000*onms/reps<<" gpuOffUs="<<1000*offms/reps<<" logicalCommonGeometryBytes="<<commonBytes<<" logicalDedicatedCapillaryBytes="<<capBytes<<" onKernelsPerCall=4 offKernelsPerCall=2 actualOffCommonAllocatedBytes="<<commonBytes<<" actualOffDedicatedCapillaryBytes=0\n";
}
